# Generated by Django 5.2.5 on 2025-11-25 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('MECANICO', 'Mecánico'), ('ENCARGADO', 'Encargado del Taller')], default='MECANICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
