# Generated by Django 5.2.5 on 2025-11-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_rol_alter_perfilusuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_movimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
