# Generated by Django 5.2.5 on 2025-12-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perfilusuario_ultimo_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zonatrabajo',
            name='ocupada',
            field=models.BooleanField(default=False),
        ),
    ]
