# Generated by Django 5.2.5 on 2025-12-01 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfilusuario_ocupada_zonatrabajo_ocupada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ocupada',
        ),
    ]
